version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${PASSWORD_SQL}
    ports:
      - "1433:1433"
    networks:
      - clima-net

  clima-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clima-api
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ClimaNotificacoesDB;User=sa;Password=${PASSWORD_SQL};TrustServerCertificate=True
    networks:
      - clima-net

networks:
  clima-net:
    driver: bridge